'use client'

import { AssetImage } from '@/components/ui/asset-image'
import { cn } from '@/lib/utils'
import type { Game } from '@/lib/types/catalog'

interface GameCoverProps {
  game: Game
  className?: string
  titleClassName?: string
  /**
   * Drop the built-in title.
   *
   * The cover anchors its own `h3` to the bottom edge, which is right for a grid
   * tile but wrong wherever the surface already writes the name into its own
   * bottom-anchored copy block — there the two layers stack and the title lands
   * on top of the call to action (the home hero: a 60px "VALORANT" sitting over
   * "Play now"). Such callers own the heading; the cover stays pure art.
   */
  hideTitle?: boolean
  /**
   * Passed straight to `next/image`. Every caller renders the cover at a
   * different width — a 25vw grid tile, a 448px modal header, a full-bleed hero —
   * and the default below is the grid case, so the other two say so explicitly.
   */
  sizes?: string
  /** Set on the first hero slide so the largest cover is not lazy-loaded. */
  priority?: boolean
}

/**
 * Game cover art, with the hashed gradient as its fallback layer.
 *
 * The artwork lives at `/covers/<id>.webp` (generated by
 * `scripts/optimize-covers.mjs`). The gradient is not dead code: it sits
 * underneath as the paint for a missing or failed file, so a cover that never
 * shipped degrades to the old placeholder instead of a hole in the grid.
 *
 * `AssetImage` (F7.5) is what makes that real: it unmounts the `img` on error, so
 * the browser's torn-page glyph never paints over the gradient. It is also why
 * this tile ships no blur data — the gradient already covers the decode window,
 * per-game and for free.
 */
export function GameCover({
  game,
  className,
  titleClassName,
  hideTitle,
  sizes = '(min-width: 1024px) 25vw, (min-width: 640px) 33vw, 50vw',
  priority,
}: GameCoverProps) {
  const [from, to] = game.cover
  const initials = game.name
    .split(/[\s:]+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0])
    .join('')
    .toUpperCase()

  return (
    <div
      className={cn('relative flex items-end overflow-hidden', className)}
      style={{ background: `linear-gradient(150deg, ${from} 0%, ${to} 85%)` }}
    >
      <div
        className="pointer-events-none absolute inset-0 opacity-20"
        style={{
          backgroundImage:
            'linear-gradient(rgba(255,255,255,0.25) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.25) 1px, transparent 1px)',
          backgroundSize: '22px 22px',
        }}
      />
      <span
        className="pointer-events-none absolute -right-2 top-1 select-none font-display text-7xl font-black leading-none text-white/10"
        aria-hidden
      >
        {initials}
      </span>
      <AssetImage
        src={`/covers/${game.id}.webp`}
        // The name is already announced by the tile's own title (or by the
        // caller's heading when `hideTitle` is set), so the art is decorative
        // and an alt repeating it would read the game twice.
        alt=""
        sizes={sizes}
        priority={priority}
        // The gradient and initials above are the fallback: they are already
        // painted, so a missing cover degrades to them and the shared plate
        // would only hide a better-looking, per-game placeholder.
        fallback="none"
        className="object-cover"
      />
      {!hideTitle && (
        <div className="relative z-10 w-full bg-gradient-to-t from-black/85 via-black/45 to-transparent p-3 pt-8">
          <h3
            className={cn(
              'font-display font-extrabold uppercase leading-tight tracking-tight text-white drop-shadow-md',
              titleClassName ?? 'text-base',
            )}
          >
            {game.name}
          </h3>
        </div>
      )}
    </div>
  )
}
