/**
 * F7.5 — LQIP (blur placeholder) generator.
 *
 *   node scripts/generate-blur.mjs
 *
 * Reads the shipped webp files and writes a base64 data URL per file into
 * `lib/assets/blur-data.generated.ts`. `next/image` cannot derive a blur for a
 * runtime `src` string (only static imports get one from the compiler), so the
 * data URLs have to exist as data.
 *
 * ## Why only some families are in here
 *
 * A blur placeholder earns its bytes only where the image *is* the surface. It
 * is dead weight where a designed layer already sits underneath:
 *
 *   - `covers/`  — the tile paints the game's own hashed gradient plus initials
 *                  below the art (see `components/game-cover.tsx`). There is no
 *                  blank frame to cover, and 67 data URLs in the client bundle
 *                  would buy nothing.
 *   - `products/` — the card paints a category icon on `surface-2`. Same story,
 *                  36 files.
 *
 * What is listed below is everything that renders full-bleed with nothing but
 * background colour behind it: the promo hero, the attract frames, the lock
 * screen wallpaper, and the fallback plate itself. That is 13 files, so the
 * generated module stays a few kilobytes rather than tens.
 *
 * ## Geometry
 *
 * 16px wide, aspect preserved, quality 20 — the placeholder is stretched over
 * a 2240px kiosk screen and then blurred by the browser, so more pixels would
 * only be more bytes. Alpha is flattened onto the app background: a transparent
 * LQIP would flash the page white on a dark screen.
 *
 * Output is deterministic (same inputs → identical file), so a re-run on an
 * unchanged `public/` produces no diff. `pnpm assets:verify` fails when a file
 * in a covered family has no entry here, which is what keeps the two in step.
 */
import { readdir, writeFile, readFile } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

const PUBLIC = path.join(process.cwd(), 'public')
const OUT = path.join(process.cwd(), 'lib', 'assets', 'blur-data.generated.ts')

/** Directories rendered full-bleed — every webp inside gets an LQIP. */
const DIRS = ['promo', 'attract']
/** Root-level one-offs, listed by name because `public/` also holds icons. */
const FILES = ['lock-bg.webp', 'fallback.webp']

/** App background (`--background`, #0a0a0b) — what alpha is flattened onto. */
const FLATTEN = { r: 10, g: 10, b: 11 }
const LQIP_WIDTH = 16

async function lqip(abs) {
  const buf = await sharp(await readFile(abs))
    .resize({ width: LQIP_WIDTH, withoutEnlargement: true })
    .flatten({ background: FLATTEN })
    .webp({ quality: 20, effort: 6 })
    .toBuffer()
  return `data:image/webp;base64,${buf.toString('base64')}`
}

async function main() {
  /** @type {Array<[string, string]>} */
  const entries = []

  for (const dir of DIRS) {
    const names = (await readdir(path.join(PUBLIC, dir)))
      .filter((n) => n.endsWith('.webp'))
      .sort()
    for (const name of names) {
      entries.push([`/${dir}/${name}`, await lqip(path.join(PUBLIC, dir, name))])
    }
  }
  for (const name of FILES.sort()) {
    entries.push([`/${name}`, await lqip(path.join(PUBLIC, name))])
  }

  const body = entries.map(([k, v]) => `  '${k}':\n    '${v}',`).join('\n')
  const bytes = entries.reduce((n, [, v]) => n + v.length, 0)

  await writeFile(
    OUT,
    `// GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// ${entries.length} placeholders, ${(bytes / 1024).toFixed(1)} KB of data URLs.
// Re-run after any change to public/promo, public/attract, lock-bg or fallback.

/** ${LQIP_WIDTH}px-wide webp LQIPs, keyed by the public path they stand in for. */
export const BLUR_DATA: Record<string, string> = {
${body}
}
`,
    'utf8',
  )

  console.log(
    `blur: ${entries.length} placeholders, ${(bytes / 1024).toFixed(1)} KB → ${path.relative(process.cwd(), OUT)}`,
  )
  for (const [k, v] of entries) console.log(`  ${k.padEnd(30)} ${v.length} B`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
