/**
 * F7.3 — asset pipeline for `public/promo/`.
 *
 * Same generator, same baked letterbox as the covers, so the band detection is
 * imported from `scripts/lib/letterbox.mjs` rather than copied. What differs is
 * the framing and the size, and both differences come from where these images
 * actually render.
 *
 *   1. Detect the bands, crop 16:9 out of the real art (`CROP_BIAS` below).
 *   2. Resize to 1024x576 webp. Larger than a cover's 800x450 because a promo
 *      banner is a *full-width* hero on a 2240px kiosk screen, not a tile in a
 *      4-column grid — and capped at 1024 because that is the generator's native
 *      width: asking sharp for 1600px would upscale, shipping bigger files with
 *      no more detail in them.
 *   3. Assert that no band line survived on a shipped edge.
 *
 * `CROP_BIAS` is lower than the covers' 0.4: the prompts push the subject into
 * the upper right and reserve the lower left for the copy, and the promo hero
 * lays a much heavier bottom scrim over the art than a cover tile does, so
 * keeping the top of the art is what protects the subject from being scrimmed.
 *
 * The banners carry **no text in the pixels** — every headline, badge and CTA is
 * DOM text over the image. That is not a stylistic choice: baked copy cannot be
 * translated by `lib/i18n`, cannot be read by a screen reader, and would have to
 * be regenerated by an artist every time the club changes a price.
 *
 * The PNGs are source assets, not deliverables: they are deleted after a
 * verified run and only the webp outputs are committed. To re-run against fresh
 * sources, drop the PNGs back into `public/promo/` (or point `PROMO_SRC` at
 * wherever they live) and run `node scripts/optimize-promo.mjs`.
 */
import { readdir, readFile, stat, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'
import { ASSERT_LEVEL, detectArtBox, edgeReadings, frameAspect } from './lib/letterbox.mjs'

const SRC_DIR = process.env.PROMO_SRC
  ? path.resolve(process.env.PROMO_SRC)
  : path.join(process.cwd(), 'public', 'promo')
const OUT_DIR = path.join(process.cwd(), 'public', 'promo')

const OUT_WIDTH = 1024
const OUT_HEIGHT = 576
const QUALITY = 82
/** Fraction of the leftover height taken off the top (0.5 = centred). */
const CROP_BIAS = 0.3
const FORCE = process.argv.includes('--force')

/** `true` when the output is missing or older than the source. */
async function needsWork(srcPath, outPath) {
  if (FORCE) return true
  try {
    const [src, out] = await Promise.all([stat(srcPath), stat(outPath)])
    return out.mtimeMs < src.mtimeMs
  } catch {
    return true
  }
}

async function main() {
  let files
  try {
    files = (await readdir(SRC_DIR)).filter((f) => f.endsWith('.png')).sort()
  } catch {
    console.log(`[promo] source directory ${SRC_DIR} does not exist — nothing to do`)
    return
  }
  if (files.length === 0) {
    // The expected state of a clean checkout: the PNGs are gone and the webp
    // outputs are what the repository carries. Not an error.
    console.log(`[promo] no source PNGs in ${SRC_DIR} — nothing to do`)
    return
  }
  await mkdir(OUT_DIR, { recursive: true })

  let sourceBytes = 0
  let outputBytes = 0
  let written = 0
  let skipped = 0
  const untouched = []
  const suspect = []

  for (const file of files) {
    const srcPath = path.join(SRC_DIR, file)
    const outPath = path.join(OUT_DIR, file.replace(/\.png$/, '.webp'))

    if (!(await needsWork(srcPath, outPath))) {
      skipped++
      continue
    }

    const input = await readFile(srcPath)
    sourceBytes += input.byteLength

    const box = await detectArtBox(input)
    const window = frameAspect(box, OUT_WIDTH / OUT_HEIGHT, CROP_BIAS)

    const top = box.top
    const bottom = box.sourceHeight - (box.top + box.height)
    const sides = box.sourceWidth - box.width
    if (top === 0 && bottom === 0 && sides === 0) untouched.push(file)

    const edges = edgeReadings(box, window)
    if (edges.some((v) => v <= ASSERT_LEVEL)) suspect.push(`${file} (edges ${edges.join('/')})`)

    const buffer = await sharp(input)
      .extract({ left: window.left, top: window.top, width: window.width, height: window.height })
      .resize(OUT_WIDTH, OUT_HEIGHT, { fit: 'cover' })
      .webp({ quality: QUALITY, effort: 5 })
      .toBuffer()

    await writeFile(outPath, buffer)
    outputBytes += buffer.byteLength
    written++

    console.log(
      `[promo] ${file.padEnd(26)} bands t${String(top).padStart(3)} b${String(bottom).padStart(3)} ` +
        `x${String(sides).padStart(3)} -> crop ${window.width}x${window.height}@${window.left},${window.top} ` +
        `-> ${(buffer.byteLength / 1024).toFixed(0)} KB`,
    )
  }

  const mb = (n) => (n / 1024 / 1024).toFixed(2)
  console.log(
    `[promo] ${written} encoded, ${skipped} up to date: ` +
      `${mb(sourceBytes)} MB PNG -> ${mb(outputBytes)} MB webp` +
      (written > 0 ? ` (avg ${(outputBytes / written / 1024).toFixed(0)} KB)` : ''),
  )
  if (untouched.length > 0) {
    console.log(`[promo] no bands detected in ${untouched.length}: ${untouched.join(', ')}`)
  }
  if (suspect.length > 0) {
    console.log(`[promo] WARNING black edge survived the crop in: ${suspect.join(', ')}`)
  }
}

main().catch((error) => {
  console.error('[promo] failed', error)
  process.exit(1)
})
