// GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// 13 placeholders, 1.4 KB of data URLs.
// Re-run after any change to public/promo, public/attract, lock-bg or fallback.

/** 16px-wide webp LQIPs, keyed by the public path they stand in for. */
export const BLUR_DATA: Record<string, string> = {
  '/promo/promo-battlepass.webp':
    'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoQAAkABUB8JZQC7ADHWTAgAP7vS9w73+Lpz12LNGusK540Kn8rUtZUAAA=',
  '/promo/promo-birthday.webp':
    'data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACQAQCdASoQAAkABUB8JYwAAudP5lgA/vDRlRogFV5GaLb0v/gp6AAA',
  '/promo/promo-cs2-weekly.webp':
    'data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoQAAkABUB8JYwAAq20goP0PAD+7p8Eaxku+LZOXzf7jvZVAAA=',
  '/promo/promo-double-coins.webp':
    'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoQAAkABUB8JagC7AEfQR8NSiAA/uzQvPqyMmWYxsj8rh3wmolz3Uqs5S2ydFpM4xHM7IAA',
  '/promo/promo-fifa-ladder.webp':
    'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoQAAkABUB8JZQAAjpm7z0AAP7w36+UHLkjrBtSeO5WNkBpVbZ1ZFjIJoqO5e2T37dYAA==',
  '/promo/promo-night-pass.webp':
    'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoQAAkABUB8JYgC7AEPApZebcgA/u6Hx/fYUb+BVaVn0BIs3tMSwkYGp/sAAA==',
  '/promo/promo-valorant-night.webp':
    'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAABwAQCdASoQAAkABUB8JYgCdAFAAAD+7qxP+0f0jF/7O1CMEK0LEYhlVYSbeG4OdMmiMQeiFxjoYLIA',
  '/promo/promo-vip-zone.webp':
    'data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAAAwAQCdASoQAAkABUB8JZQAA3AA/vAgub+BynM2zhGPceuf7GUAAA==',
  '/attract/frame-1.webp':
    'data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoQAAkABUB8JZwAAxZhS7s1OAD+71hiblWrBEFZyO0qj8dAAAA=',
  '/attract/frame-2.webp':
    'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoQAAkABUB8JYwAAn/HQbkgAP7svkSt9lNzU8F0bxW9f3v5DkC1AsL/dsAAAA==',
  '/attract/frame-3.webp':
    'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQAAkABUB8JZQC7ADp8VPX24AA/u6fm8qvcw6SPP+3k14tXyekiYZCL9p21U6gd9MCAA==',
  '/fallback.webp':
    'data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAkABUB8JZQAA3AA/vAEjf2CgAAA',
  '/lock-bg.webp':
    'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAQAgCdASoQAAkABUB8JYgCw7EUr+omYOHwAP7s1WBq0sArSnoTJHJoCyE9AYvVwAA=',
}
