/**
 * F8.1 — the interface sound set, as data the product can import.
 *
 * The audio itself is generated by `scripts/generate-sfx.mjs` from
 * `scripts/lib/sfx-manifest.mjs`, which owns the synthesis recipes, the
 * durations and the loudness ceilings. This module owns only what a *call site*
 * needs: the id, its path, and whether the cue is one of the two allowed to
 * speak over a running game.
 *
 * Numbers are intentionally absent here. Durations and peak levels would be a
 * second copy of the manifest, and a copy of a number is a number that will be
 * wrong; `pnpm assets:verify` keeps the ids in this file and the files on disk
 * in exact correspondence instead.
 *
 * The playback engine (preloading, overlap suppression, the settings-driven
 * volume and mute) is F8.2/F8.3 and lives in `lib/sfx.ts` + `hooks/use-sfx.ts`.
 * This layer stays a catalogue so those can be replaced without touching the
 * asset contract.
 */

/** Every cue the interface may play. Adding one means editing the manifest too. */
export type SfxId =
  | 'notify'
  | 'success'
  | 'error'
  | 'order-ready'
  | 'time-warning'
  | 'level-up'
  | 'admin-message'

export interface SfxEntry {
  id: SfxId
  /** Public path. Built once here so no screen hand-writes `/sfx/...`. */
  src: string
  /**
   * `true` when the cue may play **while a game is running** (F8.4).
   *
   * The rule this feeds is the difference between a launcher a player tolerates
   * and one they mute on day one: during a match the shell is silent, except for
   * the two things a player would be angry to have missed — their session time
   * running out, and an administrator addressing them.
   */
  critical: boolean
  /** What the cue means, in one line. Prevents reuse by "it sounds nice here". */
  purpose: string
}

export const SFX: Record<SfxId, SfxEntry> = {
  notify: {
    id: 'notify',
    src: '/sfx/notify.wav',
    critical: false,
    purpose: 'Generic toast — something arrived, look when convenient.',
  },
  success: {
    id: 'success',
    src: '/sfx/success.wav',
    critical: false,
    purpose: 'Action confirmed: top-up accepted, order placed, settings saved.',
  },
  error: {
    id: 'error',
    src: '/sfx/error.wav',
    critical: false,
    purpose: 'Rejected input or failed request. Low and dry, never an alarm.',
  },
  'order-ready': {
    id: 'order-ready',
    src: '/sfx/order-ready.wav',
    critical: false,
    purpose: 'Bar order is ready for pickup — the one cue heard across the room.',
  },
  'time-warning': {
    id: 'time-warning',
    src: '/sfx/time-warning.wav',
    critical: true,
    purpose: 'Session time is running out. Allowed to interrupt a game.',
  },
  'level-up': {
    id: 'level-up',
    src: '/sfx/level-up.wav',
    critical: false,
    purpose: 'Battle pass level or achievement. Reward without fanfare.',
  },
  'admin-message': {
    id: 'admin-message',
    src: '/sfx/admin-message.wav',
    critical: true,
    purpose: 'An administrator is speaking to this station. Interrupts a game.',
  },
}

/** Stable list for preloading (F8.2) and for the settings preview (F8.3). */
export const SFX_IDS = Object.keys(SFX) as SfxId[]

/** Source of truth for F8.4's gate, so no screen re-derives the exception list. */
export const isCriticalSfx = (id: SfxId): boolean => SFX[id].critical
